server:
  port: 8081

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml\

feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
      deep-seek-api:
        connect-timeout: 60000
        read-timeout: 60000

